"""Pydantic models for MAX userbot gateway requests and responses."""

from api.models.accounts import (
    Account,
    AccountListResponse,
    AccountSessionState,
    AccountStatus,
    StartLoginRequest,
    StartLoginResponse,
    VerifyLoginRequest,
    VerifyLoginResponse,
)
from api.models.channels import (
    Channel,
    ChannelListResponse,
    ChannelPermissions,
    ChannelRole,
)
from api.models.common import (
    ErrorResponse,
    PageMeta,
    SuccessResponse,
    ValidationErrorResponse,
    ValidationIssue,
)
from api.models.health import HealthResponse
from api.models.jobs import (
    CreatePublicationJobRequest,
    PublicationEvent,
    PublicationJob,
    PublicationJobListResponse,
    PublicationJobStatus,
    ReactionsHint,
    ReadyPost,
    ReadyPostButton,
    ReadyPostItem,
    ReadyPostMedia,
)
from api.models.media import Media, MediaImportRequest, MediaType, MediaUploadRequest
from api.models.posts import (
    EditPostRequest,
    InlineButton,
    InlineKeyboard,
    MediaRef,
    PinPostRequest,
    PostListResponse,
    PostMetrics,
    PostValidationResult,
    PublishedPost,
    PublishOptions,
    PublishPostRequest,
    TextFormat,
)
from api.models.schedules import (
    ScheduledPost,
    ScheduledPostListResponse,
    ScheduledPostStatus,
    SchedulePostRequest,
    UpdateScheduledPostRequest,
)
from api.models.webhooks import (
    CreateWebhookSubscriptionRequest,
    WebhookEventType,
    WebhookSubscription,
    WebhookSubscriptionListResponse,
)

__all__ = [
    "Account",
    "AccountListResponse",
    "AccountSessionState",
    "AccountStatus",
    "Channel",
    "ChannelListResponse",
    "ChannelPermissions",
    "ChannelRole",
    "CreatePublicationJobRequest",
    "CreateWebhookSubscriptionRequest",
    "EditPostRequest",
    "ErrorResponse",
    "HealthResponse",
    "InlineButton",
    "InlineKeyboard",
    "Media",
    "MediaImportRequest",
    "MediaRef",
    "MediaType",
    "MediaUploadRequest",
    "PageMeta",
    "PinPostRequest",
    "PostListResponse",
    "PostMetrics",
    "PostValidationResult",
    "PublicationEvent",
    "PublicationJob",
    "PublicationJobListResponse",
    "PublicationJobStatus",
    "PublishOptions",
    "PublishPostRequest",
    "PublishedPost",
    "ReactionsHint",
    "ReadyPost",
    "ReadyPostButton",
    "ReadyPostItem",
    "ReadyPostMedia",
    "ScheduledPost",
    "ScheduledPostListResponse",
    "ScheduledPostStatus",
    "SchedulePostRequest",
    "StartLoginRequest",
    "StartLoginResponse",
    "SuccessResponse",
    "TextFormat",
    "UpdateScheduledPostRequest",
    "ValidationErrorResponse",
    "ValidationIssue",
    "VerifyLoginRequest",
    "VerifyLoginResponse",
    "WebhookEventType",
    "WebhookSubscription",
    "WebhookSubscriptionListResponse",
]
