queries:
  - "сумка багет"
  - "юбка плиссе"
  - "топ женский"
  - "масло для губ"
  - "косметичка эстетика"
  - "ночник для комнаты"
  - "органайзер для косметики"
  - "набор канцелярии"
  - "чехол y2k"
  - "подарок подруге"
