trend_keywords:
  - "pinterest"
  - "korean"
  - "корейский"
  - "y2k"
  - "у2к"
  - "пастель"
  - "милый"
  - "эстетичный"
  - "минимализм"
  - "coquette"
  - "basic"
  - "барби"
  - "hello kitty"
  - "багет"
  - "уют"
  - "до 500"
season_keywords:
  spring:
    - "весна"
    - "8 марта"
    - "платье"
    - "юбка"
  summer:
    - "лето"
    - "купальник"
    - "топ"
    - "сандалии"
  autumn:
    - "осень"
    - "свитер"
    - "кардиган"
    - "уют"
  winter:
    - "зима"
    - "шапка"
    - "пижама"
    - "плед"
